name: Playwright Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Allure Playwright Reporter
        run: npm install -D allure-playwright

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test orangehrm-tests/specs/login.test.js --reporter=allure-playwright --project=chromium

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 7

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: allure-results/
          retention-days: 14

      - name: Generate Allure Report
        run: |
          npm install -g allure-commandline --save-dev
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure HTML Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report/
          retention-days: 14

      - name: Deploy Allure Report to GitHub Pages
        if: success()
        run: |
          git config --global user.email "aryannishen27@gmail.com"
          git config --global user.name "Aryan Nishen"
          git clone --branch gh-pages https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/nishenaryan14/Playwright.git gh-pages
          rm -rf gh-pages/*
          cp -r allure-report/* gh-pages/
          cd gh-pages
          git add .
          git commit -m "Update Allure report"
          git push origin gh-pages

      - name: Show Allure Report URL
        run: |
          echo "✅ Allure Report: https://nishenaryan14.github.io/Playwright/"


